



const DefinitionItem = ({ term, definition }) => (
  <p className="mb-2">
    <span className="font-semibold">{term}</span>{' '}
    <span className="text-gray-700">{definition}</span>
  </p>
);



const Section = ({ title, children, isTop = false }) => (
  <section className={`mb-8 ${!isTop ? 'mt-8' : ''}`}>
    <h2 className="text-2xl font-bold mb-4 text-gray-800">{title}</h2>
    <div className="text-gray-600 space-y-4">{children}</div>
  </section>
);




const page = () => {
  return (
    <div className="bg-gray-50 min-h-screen p-4 sm:p-8 font-sans">
      <div className="max-w-4xl mx-auto bg-white shadow-xl rounded-2xl p-6 sm:p-10">
        <header className="text-center mb-10">
          <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight mb-2">
            Privacy Policy
          </h1>
          <p className="text-sm text-gray-500 font-medium">Last updated: September 18, 2025</p>
        </header>

        {/* Introduction */}
        <p className="text-gray-600 leading-relaxed mb-6">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the
          Free Privacy Policy Generator.
        </p>

        {/* Interpretation and Definitions */}
        <Section title="Interpretation and Definitions">
          <p className="font-semibold text-gray-700">Interpretation</p>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <div className="mt-6">
            <h3 className="text-xl font-bold mb-4 text-gray-800">Definitions</h3>
            <DefinitionItem
              term="Account"
              definition="means a unique account created for You to access our Service or parts of our Service."
            />
            <DefinitionItem
              term="Affiliate"
              definition="means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority."
            />
            <DefinitionItem
              term="Company"
              definition='(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to subserv, Shop no 2, Amizara, Road no 2, Jawahar Nagar, Goregaon West, Mumbai 400104.'
            />
            <DefinitionItem
              term="Cookies"
              definition="are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses."
            />
            <DefinitionItem
              term="Country"
              definition="refers to: Maharashtra, India"
            />
            <DefinitionItem
              term="Device"
              definition="means any device that can access the Service such as a computer, a cellphone or a digital tablet."
            />
            <DefinitionItem
              term="Personal Data"
              definition="is any information that relates to an identified or identifiable individual."
            />
            <DefinitionItem
              term="Service"
              definition="refers to the Website."
            />
            <DefinitionItem
              term="Service Provider"
              definition="means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used."
            />
            <DefinitionItem
              term="Third-party Social Media Service"
              definition="refers to any website or any social network website through which a User can log in or create an account to use the Service."
            />
            <DefinitionItem
              term="Usage Data"
              definition="refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."
            />
            <DefinitionItem
              term="Website"
              definition="refers to Hoabl Space, accessible from https://www.hoabl.space"
            />
            <DefinitionItem
              term="You"
              definition="means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
            />
          </div>
        </Section>
        
        {/* Collecting and Using Your Personal Data */}
        <Section title="Collecting and Using Your Personal Data">
          <h3 className="text-xl font-bold mb-4 text-gray-800">Types of Data Collected</h3>
          <h4 className="font-semibold text-gray-700">Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>
          <h4 className="font-semibold text-gray-700 mt-6">Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
          </p>
          <h4 className="font-semibold text-gray-700 mt-6">Information from Third-Party Social Media Services</h4>
          <p>
            The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services: Google, Facebook, Instagram, Twitter, LinkedIn.
          </p>
          <p>
            If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account. You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
          </p>
        </Section>

        {/* Tracking Technologies and Cookies */}
        <Section title="Tracking Technologies and Cookies">
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul className="list-disc list-inside space-y-4">
            <li>
              <span className="font-semibold">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
            </li>
            <li>
              <span className="font-semibold">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.
            </li>
          </ul>
          <p className="mt-4">
            Cookies can be "Persistent" or "Session" Cookies. We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul className="list-disc list-inside space-y-4">
            <li>
              <span className="font-semibold">Necessary / Essential Cookies</span> (Type: Session Cookies, Administered by: Us, Purpose: Essential for providing website services and preventing fraudulent use of accounts.)
            </li>
            <li>
              <span className="font-semibold">Cookies Policy / Notice Acceptance Cookies</span> (Type: Persistent Cookies, Administered by: Us, Purpose: Identifies if users have accepted the use of cookies.)
            </li>
            <li>
              <span className="font-semibold">Functionality Cookies</span> (Type: Persistent Cookies, Administered by: Us, Purpose: Remembers user choices and preferences for a more personal experience.)
            </li>
          </ul>
        </Section>
        
        {/* Use of Your Personal Data */}
        <Section title="Use of Your Personal Data">
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>To provide and maintain our Service.</li>
            <li>To manage Your Account.</li>
            <li>For the performance of a contract.</li>
            <li>To contact You.</li>
            <li>To provide You with news, special offers and general information.</li>
            <li>To manage Your requests.</li>
            <li>For business transfers.</li>
            <li>For other purposes (data analysis, identifying usage trends, etc.).</li>
          </ul>
        </Section>

        {/* Sharing of Personal Data */}
        <Section title="Sharing Your Personal Information">
          <p>We may share Your personal information in the following situations:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>With Service Providers.</li>
            <li>For business transfers.</li>
            <li>With Affiliates.</li>
            <li>With business partners.</li>
            <li>With other users.</li>
            <li>With Your consent.</li>
          </ul>
        </Section>
        
        {/* Retention, Transfer, and Deletion of Data */}
        <Section title="Retention, Transfer, and Deletion of Your Personal Data">
          <h3 className="text-xl font-bold mb-4 text-gray-800">Retention of Your Personal Data</h3>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          <p>The Company will also retain Usage Data for internal analysis purposes.</p>
          <h3 className="text-xl font-bold mt-6 mb-4 text-gray-800">Transfer of Your Personal Data</h3>
          <p>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
          </p>
          <h3 className="text-xl font-bold mt-6 mb-4 text-gray-800">Delete Your Personal Data</h3>
          <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
          <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
        </Section>

        {/* Disclosure of Your Personal Data */}
        <Section title="Disclosure of Your Personal Data">
          <ul className="list-disc list-inside space-y-2">
            <li><span className="font-semibold">Business Transactions:</span> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</li>
            <li><span className="font-semibold">Law enforcement:</span> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
            <li>
              <span className="font-semibold">Other legal requirements:</span> The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect the rights or property of the Company, prevent or investigate wrongdoing, protect the personal safety of users, or protect against legal liability.
            </li>
          </ul>
        </Section>
        
        {/* Security and Privacy */}
        <Section title="Security of Your Personal Data">
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        </Section>
        
        {/* Children's Privacy */}
        <Section title="Children's Privacy">
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
        </Section>

        {/* Links to Other Websites */}
        <Section title="Links to Other Websites">
          <p>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        </Section>
        
        {/* Changes to this Privacy Policy */}
        <Section title="Changes to this Privacy Policy">
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
        </Section>
        
        {/* Contact Us */}
        <Section title="Contact Us">
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>
              <span className="font-semibold">By email:</span>{' '}
              <a href="mailto:care.subserv@gmail.com" className="text-blue-500 hover:text-blue-600 transition-colors">
                care.subserv@gmail.com
              </a>
            </li>
          </ul>
        </Section>
      </div>
    </div>
  );
};

export default page;